#!/usr/bin/python3
# -*- coding: utf-8 -*-
sqlNewTablMaster = """
CREATE TABLE "Master" ( `IDMASTER` INTEGER NOT NULL, `SHOTNAMEMASTER` TEXT, `FULLNAMEMASTER` TEXT, `BIRTHDAY` NUMERIC, `BIRTHPLACE` TEXT, `ADRESSREGISTR` TEXT, `DATARAB` TEXT, `DATAUVOLN` INTEGER, `NOTES` TEXT, `PRIZNUVOLN` INTEGER, `PRICHINAUV` TEXT, `TELEFON` TEXT, `FOTO` TEXT, `login` TEXT UNIQUE, `password` TEXT, `hash` TEXT UNIQUE, PRIMARY KEY(`IDMASTER`) )
"""

sqlNewTablDeclaration = """
CREATE TABLE `Declaration` ( `DECLID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `DECLN` INTEGER, `DECLDATA` TEXT, `KVN` INTEGER, `TELEFON` TEXT, `FIO` TEXT, `DECLARATION` TEXT, `DECLTIME` TEXT, `PODCOD` INTEGER, `MASTERID` INTEGER, `DATAVIPOLN` TEXT, `SOSTZAKAZID` INTEGER, `NOTES` TEXT, `ZAPLANIR` TEXT, `USERNAME` TEXT )
"""

slqNewTablSostzakaz = """
CREATE TABLE `Sostzakaz` ( `SOSTZAKAZID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `SOSTZAKAZ` TEXT, `COLOR` INTEGER )
"""

slqNewTablStreet = """
CREATE TABLE `Street` ( `Street` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `STREETNAME` TEXT, `DOMN` INTEGER, `DOML` TEXT )
"""

